### ISSUE TITLE
Comparing this with RolX and RoleSim role detection

### ISSUE THREAD

**Issue by BradKML** [CompNet/Orleans#1]
There are other role algorithms e.g.
- RMST-RBS in https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2014.0940 https://arxiv.org/pdf/1311.6785.pdf https://arxiv.org/pdf/1508.03165.pdf
- RoleSim https://arxiv.org/pdf/1102.3937.pdf https://arxiv.org/pdf/1102.3937.pdf https://github.com/abhishekmaha23/RoleSim-Python
- RolX https://github.com/dkaslovsky/GraphRole https://github.com/benedekrozemberczki/RolX
- Community-based PageRank https://sci-hub.se/https://link.springer.com/chapter/10.1007/978-3-642-03348-3_84
- Sociability Index https://arxiv.org/pdf/1806.08964.pdf
- https://epjdatascience.springeropen.com/track/pdf/10.1140/epjds/s13688-014-0032-y.pdf
- https://www.sciencedirect.com/science/article/pii/S1319157820304304
- https://www.sciencedirect.com/science/article/pii/S2352864819303943

Would it be reasonable to make a comparison between these algorithms and the Community Role used in this repo?

**Comment by BradKML** [comment]
https://github.com/dkaslovsky/GraphRole/issues/4 and https://github.com/abhishekmaha23/RoleSim-Python/issues/1 have been asked before.

**Comment by nicolasdugue** [comment]
Hi,
You can take a look at this paper : https://hal.archives-ouvertes.fr/hal-03197434
It is actually based on this one : https://www.researchgate.net/publication/329426018_Bringing_a_Feature_Selection_Metric_from_Machine_Learning_to_Complex_Networks_Volume_2_Proceedings_The_7th_International_Conference_on_Complex_Networks_and_Their_Applications_COMPLEX_NETWORKS_2018

The second paper relates Community roles measures to feature extraction, and the first one introduces a way to use the community roles (and thus the features extracted) to get node embeddings, i.e. vectors that can be used to solve various graphs (or texts) related tasks. Code for the first paper can be found here : https://github.com/anthonimes/SINr/
It is very fast and easy to interpret and use.

Indeed, community roles, roles embeddings and nodes embeddings are closely related ! But the aim is different, the method is different and thus the results may also be different, so comparing such methods on various tasks make sense yes.

**Comment by BradKML** [comment]
@nicolasdugue is there a repo out there that collects role detection or role embedding algorithms like what CDLib did to community detection?

**Comment by nicolasdugue** [comment]
There is the karateclub lib for node embeddings, but, to the best of my knowledge, there isn't any dedicated to role embedding. If so, I am very interested !
I am closing the issue, but feel free to contact me on nicolas.dugue[@]univ-lemans.fr if you have any questions.
You can also contact Anthony Perez and I on the SINr repo !

**Comment by BradKML** [comment]
@nicolasdugue thanks for allowing that specific repo for the communication.
